### DISCUSSION TITLE
Custom Log Source - can't see custom logs. What am I missing

### DISCUSSION THREAD

**Discussion by streamnsight** [oracle-quickstart/oci-kubernetes-monitoring#110] [Q&A]
Hello,
I'm trying to setup multiline capability for my app logs.
I see the generic logs in log analytics under Kubernetes Container Generic Logs but they are multiple entries.

I add the value overrides as follow:
```yaml
oci-onm-common:  
  fluentd:
     customLogs:
       pm-api:
           path: /var/log/containers/api-*.log
           ociLALogSourceName: "pm-api-log"
           multilineStartRegExp: /^\[\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/
           isContainerLog: true
 ```
 with the format of the beginning of my log entries being `[YYYY-MM-DDTHH:MM:SS etc...` for example 
 ```
 [2025-03-05T00:06:55+0000][DEBUG  ][p.py 623] rows:
 [
   {
"style_id": "2"
}
]
```
 
 after updating the chart, I still don't see the new log source `pm-api-log` and my logs are still split over multiple lines in Kubernetes Container Generic Log.
So what am i missing? Am I supposed to create the source `pm-api-log` in Logging Analytics, or is this stack creating it for me somehow?
Thanks for your insight
