### ISSUE TITLE
Cannot deploy logan on a node pool with taints

### ISSUE THREAD

**Issue by quyenlc** [oracle-quickstart/oci-kubernetes-monitoring#77]
I have some nodepool with taints on them.
To deploy pods on them, I must add torations to pod manifest (through deployment or daemonset, etc). But with current template file in helm chart, there is no way to do that.
Currently toleration config (in file charts/logan/templates/fluentd-daemonset.yaml) was fixed as:
```yaml
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
```
Pls support custom toleration.
Thanks.
